#include QMK_KEYBOARD_H
#include "keymap_steno.h"
 
#include "nadavspi.h"

#define LAYOUT_moonlander_wrapper(...) LAYOUT_moonlander(__VA_ARGS__)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │ESCAPE │  1  │  2  │  3  │  4  │  5  │ ASUP  │ │   +   │  6  │  7  │  8  │  9  │  0  │  ` ~  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │  TAB  │  Q  │  W  │  E  │  R  │  T  │ ASDN  │ │   -   │  Y  │  U  │  I  │  O  │  P  │   -   │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │BSPACE │A Ctr│S Opt│D Cmd│F Shf│  G  │ ASRP  │ │   =   │  H  │J Shf│K Cmd│L Opt│; Ctr│  ' "  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │CAPSWRD│  Z  │  X  │  C  │  V  │  B  │                 │  N  │  M  │ , > │ . < │ / ? │RSHIFT │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │ZOOM_MU│     │     │MO(2)│SPACE│                             │ENTER│Obsid│     │MO(3)│BSLASH │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │     TT(1)     │ │     TT(4)     │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │ LGUI  │ MO(1) │ MO(2) │ │ MO(3) │ALFRED │  MO   │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [_DEFAULT] = LAYOUT_moonlander_wrapper(
    DEFAULT_L1, KC_ASUP, KC_PLUS,  DEFAULT_R1,
    DEFAULT_L2, KC_ASDN, KC_MINUS, DEFAULT_R2,
    DEFAULT_L3, KC_ASRP, KC_EQUAL, DEFAULT_R3,
    DEFAULT_L4,                    DEFAULT_R4,
    ZOOM_MUTE, _______, _______, MO(_LOWER), KC_SPACE, TT(_RAISE), TT(_STENO), KC_ENTER, TD(TD_OBSIDIAN),  _______, MO(_LOWER), KC_BSLASH,      
    KC_LGUI, MO(_RAISE),MO(_LOWER),    MO(_LOWER), ALFRED, MO(_RAISE)
  ),  

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │ESCAPE │ F1  │ F2  │ F3  │ F4  │ F5  │       │ │       │ F6  │ F7  │ / ? │  *  │  -  │  F11  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  !  │  @  │  [  │  ]  │  |  │       │ │       │     │  7  │  8  │  9  │KP_PL│  F12  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  #  │  $  │  (  │  )  │ ` ~ │       │ │       │     │  4  │  5  │  6  │KP_PL│       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  %  │  ^  │  {  │  }  │     │                 │     │  1  │  2  │  3  │  =  │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │ , > │     │     │     │                             │  0  │ . < │ . < │  =  │       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │               │ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │       │       │       │ │       │       │       │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [1] = LAYOUT_moonlander_wrapper(
    RAISE_L1, _______, _______, RAISE_R1,
    RAISE_L2, _______, _______, RAISE_R2,
    RAISE_L3, _______, _______, RAISE_R3,
    RAISE_L4,                   RAISE_R4,
    _______, _______, _______, _______, _______,     _______,  _______,    _______, _______, _______, _______, _______,
    _______, _______, _______,                 _______, _______, _______
  ),

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │       │     │     │     │     │     │       │ │LGUI(LS│     │     │     │     │     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │       │ │LGUI(LS│MS_LE│MS_DO│MS_UP│MS_RI│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │       │ │LGUI(LS│LEFT │DOWN │ UP  │RIGHT│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │                 │MS_WH│MS_WH│MS_WH│MS_WH│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │LGUI(│LGUI(│                             │     │     │     │     │       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │LALT(LGUI(KC_SP│ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │LALT(LG│LALT(LG│       │ │       │MS_BTN2│MS_BTN1│
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [2] = LAYOUT_moonlander_wrapper(
    LOWER_L1, _______, LGUI(LSFT(KC_7)), LOWER_R1,
    LOWER_L2, _______, LGUI(LSFT(KC_6)), LOWER_R2,
    LOWER_L3, _______, LGUI(LSFT(KC_5)), LOWER_R3,
    LOWER_L4, LOWER_R4,
    _______, _______, _______, LGUI(LCTL(KC_H)),LGUI(LCTL(KC_L)),     LALT(LGUI(KC_SPACE)),  _______,       _______, _______, _______, _______, _______, 
    LALT(LGUI(KC_H)),LALT(LGUI(KC_L)),_______,                 _______, KC_MS_BTN2,     KC_MS_BTN1
  ),

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │       │     │     │     │     │     │QK_STEN│ │QK_STEN│STN_F│STN_R│STN_R│     │     │STN_PWR│
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │STN_N│STN_N│STN_N│STN_N│STN_N│       │ │       │STN_N│STN_N│STN_N│STN_N│STN_N│STN_NB │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │STN_S│STN_T│STN_P│STN_H│STN_S│       │ │       │STN_S│STN_F│STN_P│STN_L│STN_T│STN_DR │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │STN_S│STN_K│STN_W│STN_R│STN_S│                 │STN_S│STN_R│STN_B│STN_G│STN_S│STN_ZR │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │ TT(4) │     │     │     │STN_N│                             │STN_N│     │     │     │       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │    STN_NC     │ │    STN_NC     │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │ STN_A │ STN_O │       │ │       │ STN_E │ STN_U │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [_STENO] = LAYOUT_moonlander(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, QK_STENO_BOLT,                                  QK_STENO_GEMINI,STN_FN,         STN_RES1,       STN_RES2,       KC_TRANSPARENT, KC_TRANSPARENT, STN_PWR,        
    KC_TRANSPARENT, STN_N1,         STN_N2,         STN_N3,         STN_N4,         STN_N5,         KC_TRANSPARENT,                                 KC_TRANSPARENT, STN_N6,         STN_N7,         STN_N8,         STN_N9,         STN_NA,         STN_NB,         
    KC_TRANSPARENT, STN_S1,         STN_TL,         STN_PL,         STN_HL,         STN_ST1,        KC_TRANSPARENT,                                                                 KC_TRANSPARENT, STN_ST3,        STN_FR,         STN_PR,         STN_LR,         STN_TR,         STN_DR,         
    KC_TRANSPARENT, STN_S2,         STN_KL,         STN_WL,         STN_RL,         STN_ST2,                                        STN_ST4,        STN_RR,         STN_BR,         STN_GR,         STN_SR,         STN_ZR,         
    TT(_STENO), KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, STN_NC,         STN_NC,                                                                                                         STN_NC,         STN_NC,         KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, 
    STN_A,          STN_O,          KC_TRANSPARENT,                 KC_TRANSPARENT, STN_E,          STN_U
  ),
};

void caps_word_set_user(bool active) {
  ML_LED_1(active);
  ML_LED_4(active);
}
