#include QMK_KEYBOARD_H
#include "version.h"
#include "keymap_us_international.h"

#define KC_MAC_UNDO LGUI(KC_Z)
#define KC_MAC_CUT LGUI(KC_X)
#define KC_MAC_COPY LGUI(KC_C)
#define KC_MAC_PASTE LGUI(KC_V)
#define KC_PC_UNDO LCTL(KC_Z)
#define KC_PC_CUT LCTL(KC_X)
#define KC_PC_COPY LCTL(KC_C)
#define KC_PC_PASTE LCTL(KC_V)
#define ES_LESS_MAC KC_GRAVE
#define ES_GRTR_MAC LSFT(KC_GRAVE)
#define ES_BSLS_MAC ALGR(KC_6)
#define NO_PIPE_ALT KC_GRAVE
#define NO_BSLS_ALT KC_EQUAL
#define LSA_T(kc) MT(MOD_LSFT | MOD_LALT, kc)
#define BP_NDSH_MAC ALGR(KC_8)
#define SE_SECT_MAC ALGR(KC_6)
#define MOON_LED_LEVEL LED_LEVEL

#define ALFRED LCTL(KC_SPACE)
#define CLIPBOARD LALT(LGUI(KC_C))

enum custom_keycodes {
  RGB_SLD = ML_SAFE_RANGE,
};


enum tap_dance_codes {
  DANCE_0,
  DANCE_1,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │ESCAPE │  1  │  2  │  3  │  4  │  5  │ ASUP  │ │   +   │  6  │  7  │  8  │  9  │  0  │  ` ~  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │TD(DANC│  Q  │  W  │  E  │  R  │  T  │ ASDN  │ │ MINUS │  Y  │  U  │  I  │  O  │  P  │ MINUS │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │BSPACE │MT(MO│MT(MO│MT(MO│MT(MO│  G  │ ASRP  │ │ EQUAL │  H  │MT(MO│MT(MO│MT(MO│MT(MO│ QUOTE │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │CAPSWRD│  Z  │  X  │  C  │  V  │  B  │                 │  N  │  M  │COMMA│ . < │SLASH│RSHIFT │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │ MO(1) │     │     │LALT │SPACE│                             │ENTER│TD(DA│     │MO(3)│BSLASH │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │     TT(1)     │ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │ LGUI  │ MO(1) │ MO(2) │ │ MO(3) │ALFRED │  MO   │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [0] = LAYOUT_moonlander(
    KC_ESCAPE,      KC_1,           KC_2,           KC_3,           KC_4,           KC_5,           KC_ASUP,                                 KC_PLUS,        KC_6,           KC_7,           KC_8,           KC_9,           KC_0,           KC_GRAVE,       
    TD(DANCE_0),    KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,           KC_ASDN,                                 KC_MINUS,       KC_Y,           KC_U,           KC_I,           KC_O,           KC_P,           KC_MINUS,       
    KC_BSPACE,      MT(MOD_LCTL, KC_A),MT(MOD_LALT, KC_S),MT(MOD_LGUI, KC_D),MT(MOD_LSFT, KC_F),KC_G,           KC_ASRP,                                                                 KC_EQUAL,       KC_H,           MT(MOD_RSFT, KC_J),MT(MOD_RGUI, KC_K),MT(MOD_RALT, KC_L),MT(MOD_RCTL, KC_SCOLON),KC_QUOTE,       
    CAPSWRD,        KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,                                           KC_N,           KC_M,           KC_COMMA,       KC_DOT,         KC_SLASH,       KC_RSHIFT,      
    MO(1),          _______, _______, KC_LALT,        KC_SPACE,       TT(1),                                                                                                          _______, KC_ENTER,       TD(DANCE_1),    _______, MO(3),          KC_BSLASH,      
    KC_LGUI,                                                                        MO(1),MO(2),                                                                                    MO(3),          ALFRED, MO(1)
  ),  

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │ESCAPE │ F1  │ F2  │ F3  │ F4  │ F5  │       │ │       │ F6  │ F7  │SLASH│  *  │MINUS│  F11  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  !  │  @  │  [  │  ]  │  |  │       │ │       │     │  7  │  8  │  9  │KP_PL│  F12  │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  #  │  $  │  (  │  )  │ ` ~ │       │ │       │     │  4  │  5  │  6  │KP_PL│       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │  %  │  ^  │  {  │  }  │     │                 │     │  1  │  2  │  3  │EQUAL│       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │COMMA│     │     │     │                             │  0  │ . < │ . < │EQUAL│       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │               │ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │       │       │       │ │       │       │       │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [1] = LAYOUT_moonlander(
    KC_ESCAPE,      KC_F1,          KC_F2,          KC_F3,          KC_F4,          KC_F5,          _______,                                 _______, KC_F6,          KC_F7,          KC_SLASH,       KC_ASTR,        KC_MINUS,       KC_F11,         
    _______, KC_EXLM,        KC_AT,          KC_LBRACKET,    KC_RBRACKET,    KC_PIPE,        _______,                                 _______, _______, KC_7,           KC_8,           KC_9,           KC_KP_PLUS,     KC_F12,         
    _______, KC_HASH,        KC_DLR,         KC_LPRN,        KC_RPRN,        KC_GRAVE,       _______,                                                                 _______, _______, KC_4,           KC_5,           KC_6,           KC_KP_PLUS,     _______, 
    _______, KC_PERC,        KC_CIRC,        KC_LCBR,        KC_RCBR,        _______,                                 _______, KC_1,           KC_2,           KC_3,           KC_EQUAL,       _______, 
    _______, KC_COMMA,       _______, _______, _______, _______,                                                                                                 _______, KC_0,           KC_DOT,         KC_DOT,         KC_EQUAL,       _______, 
    _______, _______, _______,                 _______, _______, _______
  ),

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │       │     │     │     │     │     │       │ │LGUI(LS│     │     │     │     │     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │       │ │LGUI(LS│MS_LE│MS_DO│MS_UP│MS_RI│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │       │ │LGUI(LS│LEFT │DOWN │ UP  │RIGHT│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │     │                 │MS_WH│MS_WH│MS_WH│MS_WH│     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │LGUI(│LGUI(│                             │     │     │     │     │       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │LALT(LGUI(KC_SP│ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │LALT(LG│LALT(LG│       │ │       │MS_BTN2│MS_BTN1│
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [2] = LAYOUT_moonlander(
    _______, _______, _______, _______, _______, _______, _______,                                 LGUI(LSFT(KC_7)),_______, _______, _______, _______, _______, _______, 
    _______, _______, _______, _______, _______, _______, _______,                                 LGUI(LSFT(KC_6)),KC_MS_LEFT,     KC_MS_DOWN,     KC_MS_UP,       KC_MS_RIGHT,    _______, _______, 
    _______, _______, _______, _______, _______, _______, _______,                                                                 LGUI(LSFT(KC_5)),KC_LEFT,        KC_DOWN,        KC_UP,          KC_RIGHT,       _______, _______, 
    _______, _______, _______, _______, _______, _______,                                 KC_MS_WH_LEFT,  KC_MS_WH_DOWN,  KC_MS_WH_UP,    KC_MS_WH_RIGHT, _______, _______, 
    _______, _______, _______, LGUI(LCTL(KC_H)),LGUI(LCTL(KC_L)),LALT(LGUI(KC_SPACE)),                                                                                                _______, _______, _______, _______, _______, _______, 
    LALT(LGUI(KC_H)),LALT(LGUI(KC_L)),_______,                 _______, KC_MS_BTN2,     KC_MS_BTN1
  ),

/* ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐ ┌───────┬─────┬─────┬─────┬─────┬─────┬───────┐
 * │       │     │     │     │     │     │       │ │       │     │     │     │     │     │ RESET │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │LGUI(│     │       │ │       │     │     │     │     │     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤ ├───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │Play │Mute │Vol -│Vol +│LGUI(│       │ │       │     │     │     │     │     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┼───────┘ └───────┼─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │CLIPB│LGUI(│     │                 │     │     │     │     │     │       │
 * ├───────┼─────┼─────┼─────┼─────┼─────┘                 └─────┼─────┼─────┼─────┼─────┼───────┤
 * │       │     │     │     │     │                             │     │     │     │     │       │
 * └───────┴─────┴─────┴─────┴─────┘                             └─────┴─────┴─────┴─────┴───────┘
 *                               ┌───────────────┐ ┌───────────────┐
 *                               │               │ │               │
 *                       ┌───────┼───────┬───────┤ ├───────┬───────┼───────┐
 *                       │       │       │       │ │       │       │       │
 *                       └───────┴───────┴───────┘ └───────┴───────┴───────┘
 *                                                                      generated by [keymapviz] */
  [3] = LAYOUT_moonlander(
    _______, _______, _______, _______, _______, _______, _______,                                 _______, _______, _______, _______, _______, _______, RESET,          
    _______, _______, _______, _______, LGUI(LSFT(KC_SPACE)),_______, _______,                                 _______, _______, _______, _______, _______, _______, _______, 
    _______, KC_MEDIA_PLAY_PAUSE,KC_AUDIO_MUTE,  KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,LGUI(LSFT(KC_M)),_______,                                                                 _______, _______, _______, _______, _______, _______, _______, 
    _______, _______, _______, CLIPBOARD,LGUI(KC_BSLASH),_______,                                 _______, _______, _______, _______, _______, _______, 
    _______, _______, _______, _______, _______, _______,                                                                                                 _______, _______, _______, _______, _______, _______, 
    _______, _______, _______,                 _______, _______, _______
  ),
};

extern rgb_config_t rgb_matrix_config;

void keyboard_post_init_user(void) {
  rgb_matrix_enable();
}

const uint8_t PROGMEM ledmap[][DRIVER_LED_TOTAL][3] = {
    [0] = { {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {31,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0} },

    [1] = { {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {252,119,255}, {252,119,255}, {252,119,255}, {0,0,0}, {0,0,0}, {252,119,255}, {252,119,255}, {252,119,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,245,245}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {41,255,255}, {41,255,255}, {41,255,255}, {41,255,255}, {41,255,255}, {41,255,255}, {219,255,255}, {219,255,255}, {219,255,255}, {41,255,255}, {41,255,255}, {219,255,255}, {219,255,255}, {219,255,255}, {0,0,0}, {0,0,0}, {219,255,255}, {219,255,255}, {219,255,255}, {219,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0} },

    [2] = { {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {74,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {74,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {74,255,255}, {74,255,255}, {0,0,0}, {29,255,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {129,5,130}, {74,223,130}, {129,5,130}, {0,0,0}, {0,0,0}, {129,5,130}, {74,223,130}, {129,5,130}, {0,0,0}, {0,0,0}, {129,5,130}, {74,223,130}, {129,5,130}, {0,0,0}, {0,0,0}, {129,5,130}, {74,223,130}, {129,5,130}, {152,255,255}, {152,255,255}, {152,255,255}, {129,5,130}, {129,5,130}, {0,0,0}, {0,0,0} },

    [3] = { {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {157,159,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {157,159,255}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {157,159,255}, {0,249,229}, {0,0,0}, {0,0,0}, {0,249,229}, {157,159,255}, {0,249,229}, {0,0,0}, {0,0,0}, {0,0,0}, {82,229,216}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {50,153,244}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0}, {0,0,0} },

};

void set_layer_color(int layer) {
  for (int i = 0; i < DRIVER_LED_TOTAL; i++) {
    HSV hsv = {
      .h = pgm_read_byte(&ledmap[layer][i][0]),
      .s = pgm_read_byte(&ledmap[layer][i][1]),
      .v = pgm_read_byte(&ledmap[layer][i][2]),
    };
    if (!hsv.h && !hsv.s && !hsv.v) {
        rgb_matrix_set_color( i, 0, 0, 0 );
    } else {
        RGB rgb = hsv_to_rgb( hsv );
        float f = (float)rgb_matrix_config.hsv.v / UINT8_MAX;
        rgb_matrix_set_color( i, f * rgb.r, f * rgb.g, f * rgb.b );
    }
  }
}

void rgb_matrix_indicators_user(void) {
  if (keyboard_config.disable_layer_led) { return; }
  switch (biton32(layer_state)) {
    case 0:
      set_layer_color(0);
      break;
    case 1:
      set_layer_color(1);
      break;
    case 2:
      set_layer_color(2);
      break;
    case 3:
      set_layer_color(3);
      break;
   default:
    if (rgb_matrix_get_flags() == LED_FLAG_NONE)
      rgb_matrix_set_color_all(0, 0, 0);
    break;
  }
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case RGB_SLD:
      if (record->event.pressed) {
        rgblight_mode(1);
      }
      return false;
  }
  return true;
}

typedef struct {
    bool is_press_action;
    uint8_t step;
} tap;

enum {
    SINGLE_TAP = 1,
    SINGLE_HOLD,
    DOUBLE_TAP,
    DOUBLE_HOLD,
    DOUBLE_SINGLE_TAP,
    MORE_TAPS
};

static tap dance_state[2];

uint8_t dance_step(qk_tap_dance_state_t *state);

uint8_t dance_step(qk_tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}


void on_dance_0(qk_tap_dance_state_t *state, void *user_data);
void dance_0_finished(qk_tap_dance_state_t *state, void *user_data);
void dance_0_reset(qk_tap_dance_state_t *state, void *user_data);

void on_dance_0(qk_tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_TAB);
        tap_code16(KC_TAB);
        tap_code16(KC_TAB);
    }
    if(state->count > 3) {
        tap_code16(KC_TAB);
    }
}

void dance_0_finished(qk_tap_dance_state_t *state, void *user_data) {
    dance_state[0].step = dance_step(state);
    switch (dance_state[0].step) {
        case SINGLE_TAP: register_code16(KC_TAB); break;
        case SINGLE_HOLD: register_code16(LSFT(KC_TAB)); break;
        case DOUBLE_TAP: register_code16(KC_TAB); register_code16(KC_TAB); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_TAB); register_code16(KC_TAB);
    }
}

void dance_0_reset(qk_tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state[0].step) {
        case SINGLE_TAP: unregister_code16(KC_TAB); break;
        case SINGLE_HOLD: unregister_code16(LSFT(KC_TAB)); break;
        case DOUBLE_TAP: unregister_code16(KC_TAB); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_TAB); break;
    }
    dance_state[0].step = 0;
}
void on_dance_1(qk_tap_dance_state_t *state, void *user_data);
void dance_1_finished(qk_tap_dance_state_t *state, void *user_data);
void dance_1_reset(qk_tap_dance_state_t *state, void *user_data);

void on_dance_1(qk_tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(LGUI(LSFT(KC_SCOLON)));
        tap_code16(LGUI(LSFT(KC_SCOLON)));
        tap_code16(LGUI(LSFT(KC_SCOLON)));
    }
    if(state->count > 3) {
        tap_code16(LGUI(LSFT(KC_SCOLON)));
    }
}

void dance_1_finished(qk_tap_dance_state_t *state, void *user_data) {
    dance_state[1].step = dance_step(state);
    switch (dance_state[1].step) {
        case SINGLE_TAP: register_code16(LGUI(LSFT(KC_SCOLON))); break;
        case DOUBLE_TAP: register_code16(LALT(LGUI(LSFT(KC_D)))); break;
        case DOUBLE_SINGLE_TAP: tap_code16(LGUI(LSFT(KC_SCOLON))); register_code16(LGUI(LSFT(KC_SCOLON)));
    }
}

void dance_1_reset(qk_tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state[1].step) {
        case SINGLE_TAP: unregister_code16(LGUI(LSFT(KC_SCOLON))); break;
        case DOUBLE_TAP: unregister_code16(LALT(LGUI(LSFT(KC_D)))); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(LGUI(LSFT(KC_SCOLON))); break;
    }
    dance_state[1].step = 0;
}

qk_tap_dance_action_t tap_dance_actions[] = {
        [DANCE_0] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_0, dance_0_finished, dance_0_reset),
        [DANCE_1] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_1, dance_1_finished, dance_1_reset),
};

bool get_custom_auto_shifted_key(uint16_t keycode, keyrecord_t *record) {
    if (IS_MT(keycode)){return true;}
    return false;
}

void caps_word_set_user(bool active) {
  ML_LED_1(active);
  ML_LED_4(active);
}

