#include QMK_KEYBOARD_H

enum layers {
    _QWERTY,
    _RAISE,
    _LOWER,
    _ADJUST
};


#define RAISE MO(_RAISE)
#define LOWER MO(_LOWER)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
 
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ ESC  │  1   │  2   │  3   │  4   │  5   │                    │  6   │  7   │  8   │  9   │  0   │ ` ~  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ TAB  │  Q   │  W   │  E   │  R   │  T   │                    │  Y   │  U   │  I   │  O   │  P   │ MINS │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │BSPACE│A Ctrl│S Opt │D Cmd │F Shft│  G   │                    │  H   │J Shft│K Cmd │L Opt │; Ctrl│ ' "  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┼──────┤
 * │ LSFT │  Z   │  X   │  C   │  V   │  B   │ LBRC  │    │ RBRC  │  N   │  M   │ COMM │ . <  │ SLSH │ RSFT │
 * └──────┴──────┴───┬──┴───┬──┴───┬──┴───┬─┬┴──────┬┘    └┬──────┴┬──┬──┴───┬──┴───┬──┴───┬──┴──────┴──────┘
 *                   │ LALT │ LGUI │ SPC  │ ╵LOWER  ╵      ╵RAISE  ╵  │ ENT  │ BSPC │ RGUI │
 *                   │      │      │      ├┐                        ╷ │      │      │      │
 *                   └──────┴──────┴──────┴┴──────╴          ╶──────┴─┴──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */

 [_QWERTY] = LAYOUT(
  KC_ESC,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                     KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_GRV,
  KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                     KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_MINS,
  KC_BSPACE,      MT(MOD_LCTL, KC_A),MT(MOD_LALT, KC_S),MT(MOD_LGUI, KC_D),MT(MOD_LSFT, KC_F),KC_G,                                                         KC_H,           MT(MOD_RSFT, KC_J),MT(MOD_RGUI, KC_K),MT(MOD_RALT, KC_L),MT(MOD_RCTL, KC_SCOLON),KC_QUOTE,       
  KC_LSFT,  KC_Z,   KC_X,    KC_C,        KC_V,    KC_B, KC_LBRC,  KC_RBRC,  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,  KC_RSFT,
                          KC_LALT,    KC_LGUI, KC_SPC, KC_LGUI,  RAISE, KC_ENT,  _______, KC_RGUI
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │      │      │      │      │      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  F1  │  F2  │  F3  │  F4  │  F5  │  F6  │                    │  F7  │  F8  │  F9  │ F10  │ F11  │ F12  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ ` ~  │  !   │  @   │  #   │  $   │  %   │                    │  ^   │  &   │  *   │  (   │  )   │  ~   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │       │    │       │      │  _   │  +   │  {   │  }   │  |   │
 * └──────┴──────┴───┬──┴───┬──┴───┬──┴───┬─┬┴──────┬┘    └┬──────┴┬──┬──┴───┬──┴───┬──┴───┬──┴──────┴──────┘
 *                   │      │      │      │ ╵       ╵      ╵       ╵  │      │      │      │
 *                   │      │      │      ├┐                        ╷ │      │      │      │
 *                   └──────┴──────┴──────┴┴──────╴          ╶──────┴─┴──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */
[_LOWER] = LAYOUT(
  _______, _______, _______, _______, _______, _______,                   _______, _______, _______,_______, _______, _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,
  KC_GRV, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                   KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TILD,
  _______, _______, _______, _______, _______, _______, _______, _______, XXXXXXX, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
                             _______, _______, _______, _______, _______,  _______, _______, _______
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │RGB_MO│RGB_RM│RGB_SA│RGB_SA│RGB_VA│RGB_VA│                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ ` ~  │  1   │  2   │  3   │  4   │  5   │                    │  6   │  7   │  8   │  9   │  0   │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  F1  │  F2  │  F3  │  F4  │  F5  │  F6  │                    │      │ LEFT │ DOWN │  UP  │ RGHT │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┼──────┤
 * │  F7  │  F8  │  F9  │ F10  │ F11  │ F12  │RGB_TO │    │       │  +   │ MINS │ EQL  │ LBRC │ RBRC │ \ |  │
 * └──────┴──────┴───┬──┴───┬──┴───┬──┴───┬─┬┴──────┬┘    └┬──────┴┬──┬──┴───┬──┴───┬──┴───┬──┴──────┴──────┘
 *                   │      │      │      │ ╵       ╵      ╵       ╵  │      │      │      │
 *                   │      │      │      ├┐                        ╷ │      │      │      │
 *                   └──────┴──────┴──────┴┴──────╴          ╶──────┴─┴──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */

[_RAISE] = LAYOUT(
  RGB_MOD, RGB_RMOD,RGB_SAI, RGB_SAD, RGB_VAI, RGB_VAD,                     _______, _______, _______, _______, _______, _______,
  KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    _______,
  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                       XXXXXXX, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX,
  KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,   RGB_TOG, _______,  KC_PLUS, KC_MINS, KC_EQL,  KC_LBRC, KC_RBRC, KC_BSLS,
                             _______, _______, _______,  _______, _______,  _______, _______, _______
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │      │      │      │      │      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │       │    │       │      │      │      │      │      │      │
 * └──────┴──────┴───┬──┴───┬──┴───┬──┴───┬─┬┴──────┬┘    └┬──────┴┬──┬──┴───┬──┴───┬──┴───┬──┴──────┴──────┘
 *                   │      │      │      │ ╵       ╵      ╵       ╵  │      │      │      │
 *                   │      │      │      ├┐                        ╷ │      │      │      │
 *                   └──────┴──────┴──────┴┴──────╴          ╶──────┴─┴──────┴──────┴──────┘
 *                                                                               generated by [keymapviz] */

  [_ADJUST] = LAYOUT(
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                             _______, _______, _______, _______, _______,  _______, _______, _______
  )
};

layer_state_t layer_state_set_user(layer_state_t state) {
   return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
}

bool get_custom_auto_shifted_key(uint16_t keycode, keyrecord_t *record) {
    if (IS_MT(keycode)){return true;}
    return false;
}