#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 185
#define RETRO_SHIFT 300
#define PERMISSIVE_HOLD
#define AUTO_SHIFT_TIMEOUT 160
#define AUTO_SHIFT_NO_SETUP
#define NO_AUTO_SHIFT_ALPHA
#define TAPPING_TOGGLE 1
#define LEADER_TIMEOUT 300

#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_DELAY
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#define COMBO_TERM 40

#ifdef OLED_ENABLE
#define OLED_BRIGHTNESS 5
#endif
